fix: update pinact to v2.0.0

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -63,14 +63,31 @@ runs:
           cat "$tempfile"
           echo EOF
         } >> "$GITHUB_OUTPUT"
+
+    - shell: bash
+      run: |
+        set -euo pipefail
+        if echo "$FILES" | ! xargs -r pinact run --check; then
+          echo "::error:: GitHub Actions aren't pinned."
+          exit 1
+        fi
+      if: fromJSON(inputs.skip_push) && steps.check_changed.outputs.value == 'true'
+      env:
+        FILES: ${{ steps.files.outputs.value }}
+        AQUA_GLOBAL_CONFIG: ${{env.AQUA_GLOBAL_CONFIG}}:${{steps.aqua_config.outputs.value}}
+
     - shell: bash
       run: echo "$FILES" | xargs -r pinact run
+      if: |
+        ! fromJSON(inputs.skip_push) && steps.check_changed.outputs.value == 'true'
       env:
         FILES: ${{ steps.files.outputs.value }}
         AQUA_GLOBAL_CONFIG: ${{env.AQUA_GLOBAL_CONFIG}}:${{steps.aqua_config.outputs.value}}
 
     - shell: bash
       id: check_changed
+      if: |
+        ! fromJSON(inputs.skip_push) && steps.check_changed.outputs.value == 'true'
       env:
         FILES: ${{ steps.files.outputs.value }}
       run: |
@@ -81,12 +98,6 @@ runs:
         else
           echo "value=true" >> "$GITHUB_OUTPUT"
         fi
-
-    - shell: bash
-      if: fromJSON(inputs.skip_push) && steps.check_changed.outputs.value == 'true'
-      run: |
-        echo "::error:: GitHub Actions aren't pinned."
-        exit 1
 
     - shell: bash
       if: |
